# Generated by Django 5.0.3 on 2024-03-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_telefone_aluno_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='celular',
            new_name='telefone',
        ),
    ]
